### ISSUE TITLE
CBench: msgbuf_read() = 0

### ISSUE THREAD

**Issue by dfarrell07** [dfarrell07/wcbench#16]
I'm seeing this error pretty frequently, with no obvious pattern. I'm marking this as a bug, but it's really a bug in CBench.

```
cbench: controller benchmarking tool
   running in mode 'latency'
   connecting to controller at 172.18.14.26:6633 
   faking 256 switches :: 10 tests each; 10000 ms per test
   with 10000000 unique source MACs per switch
   learning destination mac addresses before the test
   starting test with 0 ms delay after features_reply
   ignoring first 1 "warmup" and last 0 "cooldown" loops
   connection delay of 0ms per 1 switch(es)
   debugging info is off
controller msgbuf_read() = 0:   closed connection ... exiting
```

**Comment by lucar91** [comment]
hi, did you work with cbench anymore? I'm doing stress tests on some controllers, when I insert too many switches, the controller error appears 

"msgbuf_read () = 0: closed connection ... exiting"

I wanted to know if it was confirmed that it is a bug in cbench or if maybe there is some error in the controller settings ...
Thanks in advance

**Comment by dfarrell07** [comment]
Hey @lucar91, I'm not using CBench or WCBench anymore. These were really early testing tools in SDN, since then lots of other, better ones have been developed by the now-much-larger test community. You may want to take a look at Browbeat, for example.

https://jira.opnfv.org/browse/CPERF-9

**Comment by lucar91** [comment]
Thanks a lot for the answer.
The problem with browbet is memory, I have 4 gigabytes of ram and if I have not misunderstood browbet is virtualized and to do good tests it needs a lot of memory. Can you advise me more?

**Comment by dfarrell07** [comment]
Yeah, it requires a mountain of RAM, I think at least 32GB to run TripleO deployment and test.

Maybe a better path for you would be to work with upstream communities to leverage their CI infra for whatever testing you have in mind. They likely already have something to start from, or maybe even already have whatever you're looking for. At least you'd have access to cloud infra with lots of resources for running jobs, and whatever work you end up doing would support upstream development efforts.

If you want to reach out to the relevant ODL group, join the integration-dev list and send your query there.

https://lists.opendaylight.org/mailman/listinfo/integration-dev

Maybe an even better option is to join the OPNFV SDN Controller Perf testing call and talk with folks about whatever you're trying to do. That's actually the main place ODL perf tests are discussed, most of the relevant experts are there. If you're interested in another controller that's okay too, CPerf is scoped to cover all SDN perf testing, although it's only ODL folks who actually show up.

https://wiki.opnfv.org/display/meetings/CPerf

**Comment by lucar91** [comment]
Thank you very much for your help, you have been very kind

**Comment by dfarrell07** [comment]
No problem, glad to help. :)
