### ISSUE TITLE
Error Running ./wcbench.sh -o

### ISSUE THREAD

**Issue by osm1n** [dfarrell07/wcbench#55]
I was able to get the vagrant running and ssh into it but after i "cd wcbench" and then ran the commands to install the opendaylight which is "./wcbench.sh -o". I encountered these errors: ./wcbench.sh: 47: ./wcbench.sh: declare: not found
./wcbench.sh: 50: ./wcbench.sh: Syntax error: "(" unexpected

Please how do i go about solving this. I am running the wcbench on a Mac OS X.

Thank You as always :)

**Comment by osm1n** [comment]
Figured a way around, i changed the first line in the script "wcbench.sh" to #!/bin/bash

**Comment by dfarrell07** [comment]
> Figured a way around, i changed the first line in the script "wcbench.sh" to #!/bin/bash

Humm, that's interesting. It's generally best, and way more portable, to use `#!/usr/bin/env bash` as the shebang. See [this StackOverflow question](http://stackoverflow.com/questions/16365130/the-difference-between-usr-bin-env-bash-and-usr-bin-bash) for details.

And you say you were doing this in the Vagrant environment? That's all the more strange, as it's very well tested and should be consistent without regard to OSX vs Linux vs whatever as the host OS.

**Comment by dfarrell07** [comment]
> Thank You as always :)

Thank **you** for using WCBench and raising issues, consistent with the [Contact](https://github.com/dfarrell07/wcbench#user-content-contact) section of the README. :)
