### ISSUE TITLE
Stuck at: Will repeatedly attempt connecting to Karaf shell until it's ready

### ISSUE THREAD

**Issue by osm1n** [dfarrell07/wcbench#56]
After running ./wcbench.sh -o am stuck at 

Will repeatedly attempt connecting to Karaf shell until it's ready

and its been like that for hours now, no response or an error.

Please help

**Comment by dfarrell07** [comment]
Are you running in a Vagrant environment or one you manually configured? Generally, can you tell me more about the setup?

> Will repeatedly attempt connecting to Karaf shell until it's ready

This normally implies that ODL isn't up and listening on the Karaf shell port, or that the place you're running the script from can't access ODL's Karaf shell port over the network.

> and its been like that for hours now, no response or an error.

It shouldn't take more than a minute or so, normally ~15 seconds.

**Comment by osm1n** [comment]
My setup:
I have a macbook pro which i installed vagrant on and virtualbox. 
then i cloned the wcbench using "git clone https://github.com/dfarrell07/wcbench.git" repository in my home folder on the macbook.

then i "cd into wcbench" directory and typed vagrant up
this is the box am using for vagrant: http://puppet-vagrant-boxes.puppetlabs.com/debian-70rc1-x64-vbox4210.box"

After vagrant up the box loaded successfully, then i typed vagrant ssh
and i am into the vagrant environment.

First i cd into wcbench, then i installed cbench using "./wcbench.sh -c"
then installed the opendaylight distribution using "./wcbench.sh -i"

both cbench and opendaylight were installed successfully. 
then i i wanted to run the opendaylight controller with this command: "./wcbench.sh -o"
Thats where i am stuck for many hours and believe me i slept and woke up its still like that showing:

Will repeatedly attempt connecting to Karaf shell until it's ready. attached is screen grab of it.

![vagrant](https://cloud.githubusercontent.com/assets/4988486/6097117/0f0c89a2-afeb-11e4-95eb-b924376d98e2.jpg)

**Comment by dfarrell07** [comment]
> this is the box am using for vagrant: http://puppet-vagrant-boxes.puppetlabs.com/debian-70rc1-x64-vbox4210.box"

I'm not sure I understand what you mean by this bit. The [Vagrantfile](https://github.com/dfarrell07/wcbench/blob/master/Vagrantfile) configures which box to use, so unless you modified it you're using `chef/fedora-20`.

```
    # Build Vagrant box based on Fedora 20
    config.vm.box = "chef/fedora-20"
```

> First i cd into wcbench, then i installed cbench using "./wcbench.sh -c"
then installed the opendaylight distribution using "./wcbench.sh -i"

This is done in the [Vagrantfile](https://github.com/dfarrell07/wcbench/blob/master/Vagrantfile), so you don't need to bother with it yourself.

```
    # Install OpenDaylight and CBench with verbose output
    config.vm.provision "shell", inline: 'su -c "/home/vagrant/wcbench/wcbench.sh -vci" vagrant'
```

> then i i wanted to run the opendaylight controller with this command: "./wcbench.sh -o"

You could use the flags `-vo` to output verbose information, for better debugging.

> Thats where i am stuck for many hours and believe me i slept and woke up its still like that showing:

I wasn't able to reproduce this, unfortunately.

```
# In a freshly built Vagrant env
[vagrant@localhost wcbench]$ ./wcbench.sh -o
Starting OpenDaylight
Installing sshpass. It's used for issuing ODL config.
Will repeatedly attempt connecting to Karaf shell until it's ready
Issued `dropAllPacketsRpc on` command via Karaf shell to localhost:8101
Issued `log:set ERROR` command via Karaf shell to localhost:8101
```

You can check if the Karaf shell port is open like this:

```
[vagrant@localhost ~]$ netstat -anp | grep 8101
tcp6       0      0 :::8101                 :::*                    LISTEN      6143/java           
tcp6       0      0 ::1:60178               ::1:8101                TIME_WAIT   -                   
```

You can attempt manually sshing into the Karaf shell like this:

```
[vagrant@localhost wcbench]$ ssh karaf@localhost -p 8101
The authenticity of host '[localhost]:8101 ([::1]:8101)' can't be established.
DSA key fingerprint is ab:36:70:b7:8d:6f:9e:41:fe:45:63:92:c3:47:16:6d.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[localhost]:8101' (DSA) to the list of known hosts.
Authenticated with partial success.
Password authentication
Password: 
                                                                                           
    ________                       ________                .__  .__       .__     __       
    \_____  \ ______   ____   ____ \______ \ _____  ___.__.|  | |__| ____ |  |___/  |_     
     /   |   \\____ \_/ __ \ /    \ |    |  \\__  \<   |  ||  | |  |/ ___\|  |  \   __\    
    /    |    \  |_> >  ___/|   |  \|    `   \/ __ \\___  ||  |_|  / /_/  >   Y  \  |      
    \_______  /   __/ \___  >___|  /_______  (____  / ____||____/__\___  /|___|  /__|      
            \/|__|        \/     \/        \/     \/\/            /_____/      \/          
                                                                                           

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown OpenDaylight.

opendaylight-user@root>
```

You could also install nmap to verify that the Karaf shell port is open:

```
[vagrant@localhost wcbench]$ sudo yum install -y nmap[vagrant@localhost wcbench]$ sudo yum install -y nmap
# snip
Installed:
  nmap.x86_64 2:6.45-1.fc20                                                     

Dependency Installed:
  nmap-ncat.x86_64 2:6.45-1.fc20                                                

Complete!
```

Run it like this:

```
[vagrant@localhost wcbench]$ nmap -Pn -p 8101 localhost

Starting Nmap 6.45 ( http://nmap.org ) at 2015-02-08 19:34 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00013s latency).
Other addresses for localhost (not scanned): 127.0.0.1
PORT     STATE SERVICE
8101/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.03 seconds
```

**Comment by osm1n** [comment]
I ran nmap against the port number and realized it was closed. Also i ran the command "./wcbench.sh -vo" and realized it was the port number which was the problem.

So i have another VM running SDN_HUB image with all the controllers installed. So i just changed the wcbench.sh controller IP to point to my VM's IP and ran Opendaylight remotely and it worked :)

Thank You very much

Now am trying to copy the results.csv to my macbook so that i can study the results because i need this information for my thesis work. 

Thank You again.

**Comment by dfarrell07** [comment]
Good to hear you got it working. :)

> Now am trying to copy the results.csv to my macbook so that i can study the results because i need this information for my thesis work.

FYI (as [noted](https://github.com/dfarrell07/wcbench#detailed-walkthrough-vagrant) in the README), in Vagrant environments the Vagrant dir is hard-linked to the root of the project. So, in the case of WCBench the Vagrant dir is configured to be `/home/vagrant/wcbench`:

```
     # Drop code in /home/vagrant/wcbench, not /vagrant
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder ".", "/home/vagrant/wcbench"
```

Dropping `results.csv` in there will make it accessible in your host system via the project root.

**Comment by osm1n** [comment]
Thank You

Got the result in my root directory :)

up next for me is using the stats.py.
