### ISSUE TITLE
parameters information (wcbench)

### ISSUE THREAD

**Issue by stefanoperone** [dfarrell07/wcbench#59]
Hi Daniel,

I'd like to find out more  about "cbench_max, cbench_min, cbench_avg, one_min_load, five_min_load, fifteen_min_load" parameters? 

What are exactly this parameters? How are they calculated??
Thanks :)

**Comment by stefanoperone** [comment]
With these parameters:

![param](https://cloud.githubusercontent.com/assets/11172791/6430179/61f60750-bfff-11e4-9240-c90165073466.png)

I don't understand these values:

![risu](https://cloud.githubusercontent.com/assets/11172791/6430185/977518b2-bfff-11e4-978a-7c21dde700f9.png)

and the average responses/sec (817.41),  are the answers that "switches" riceve by "controller"?

**Comment by dfarrell07** [comment]
> What are exactly this parameters?

They are described in detail in the [WCBench Results section of the README](https://github.com/dfarrell07/wcbench#user-content-wcbench-results).

>  How are they calculated??

[This array](https://github.com/dfarrell07/wcbench/blob/master/wcbench.sh#L61-L69) contains most of the commands used to gather system stats, including all of the `*_load` ones you asked about. The CBench min/max/avg values are parsed from CBench's result output. [Here's the relevant code](https://github.com/dfarrell07/wcbench/blob/master/wcbench.sh#L443-L447).

> are the answers that "switches" riceve by "controller"?

I don't think I understand what you mean by this - can you restate it more clearly?

You can find general information about system load from many places, including [this wiki article](http://en.wikipedia.org/wiki/Load_%28computing%29).

**Comment by stefanoperone** [comment]
Daniel excuse me, 
I wouldn't be wrong;

"CBench is a somewhat classic SDN controller benchmark tool. It blasts a controller with OpenFlow packet-in messages and counts the rate of flow mod messages returned."

Is "cbench_avg" parameter calculated according to these messages returned?

**Comment by dfarrell07** [comment]
> Is "cbench_avg" parameter calculated according to these messages returned?

Yes, it's the average packet_ins/flow_mods per second.

My [slides from LinuxCon](http://slides.com/dfarrell07/opendaylight-performace#/3/1) provide a pretty good overview of CBench's algorithm.

**Comment by stefanoperone** [comment]
Perfect ;)
Thanks you !!
