### ISSUE TITLE
CBench installation fails

### ISSUE THREAD

**Issue by Jaanki** [dfarrell07/wcbench#60]
Hi

I cloned WCBench repository from git on Ubuntu 14.04 bare metal machine. From wcbecnh directory, I am running ./wcbench.sh -c to install CBench. Ouput is
  CBench is not installed
  Installing CBench dependencies
  Cloning CBench repo into /home/controller1/oflops
  Cloning openflow source code into /home/controller1/openflow
  Building oflops/configure file
  Building CBench
  CBench is not installed
  Failed to install CBench

I changed #!/usr/bin/env bash to #!/bin/bash, tried with sudo, and no success. Getting the same error. 

Any help will be very much appreciated.

**Comment by dfarrell07** [comment]
WCBench is only tested on Fedora (should work on CentOS). It does a bunch of [yum-specific stuff](https://github.com/dfarrell07/wcbench/blob/master/wcbench.sh#L160-L166), which (at a minimum) would cause failures on Ubuntu 14.04.

One goal of the Vagrantfile is to support people with different host OSs - you can[ trivially `vagrant up` a working dev env](https://github.com/dfarrell07/wcbench#user-content-detailed-walkthrough-vagrant) (build with Fedora 20).

Else, PRs to add Ubuntu support are welcome! :)

**Comment by Jaanki** [comment]
Thank you so much for the reply. I will try with vagrant.

**Comment by Jaanki** [comment]
Where do I download chef/fedora-20 box from?

**Comment by Jaanki** [comment]
Found it...Fedora VM is up and running:)

**Comment by dfarrell07** [comment]
> Where do I download chef/fedora-20 box from?
>> Found it...Fedora VM is up and running:)

For anyone else reading this, Vagrant handles the box download for you in almost all situations.

For example:

```
[~]$ mkdir vagrant_demo && cd vagrant_demo                                                                                                                                                                                             13:48:06
[~/vagrant_demo]$ vagrant init -m chef/fedora-20                                                                                                                                                                                       13:48:17
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
[~/vagrant_demo]$ cat Vagrantfile                                                                                                                                                                                                      13:48:28
Vagrant.configure(2) do |config|
  config.vm.box = "chef/fedora-20"
end
[~/vagrant_demo]$ vagrant up &> /dev/null                                                                                                                                                                                              13:48:30
[~/vagrant_demo]$ vagrant status                                                                                                                                                                                                       13:49:13
Current machine states:

default                   running (virtualbox)

The VM is running. To stop this VM, you can run `vagrant halt` to
shut it down forcefully, or you can run `vagrant suspend` to simply
suspend the virtual machine. In either case, to restart it again,
simply run `vagrant up`.
[~/vagrant_demo]$ vagrant ssh                                                                                                                                                                                                          13:49:48
Last login: Fri Dec 20 18:02:34 2013 from 10.0.2.2
[vagrant@localhost ~]$
```

See the (outstanding) [Vagrant docs](http://docs.vagrantup.com/v2/getting-started/) for more info.
