### ISSUE TITLE
CBench: reduce switch or increase core error

### ISSUE THREAD

**Issue by dfarrell07** [dfarrell07/wcbench#61]
***Copying an email to this Issues so I can answer it publicly (docs for others, etc).***

I cloned WCBench repo from git hub. Ran command vagrant up. It gave error saying box chef/fedora-20 is not found. So I added the box by 

vagrant box add chef/fedora-20 https://atlas.hashicorp.com/chef/boxes/fedora-20

vagrant up then started a VM. sshed into the VM.

Ran ./wcbench.sh -ci
./wcbench -o
./wcbench -r

This is giving following error

Collecting pre-test stats
Running CBench against ODL on localhost:6633
Collecting post-test stats
Collecting time-irrelevant stats
WARNING: Error occurred: Failed to parse CBench average
This is an issue with CBench or ODL, not WCBench.
May need to reduce NUM_SWITCHES or allocate more CPU cores
See: /home/vagrant/cbench.log
See: https://github.com/dfarrell07/wcbench/issues/16

I have reduced NUM_SWITCHES to 6 in wcbench.sh file and no. of cores increased to8 in Vagrant up. Yet I am getting this error.

**Comment by dfarrell07** [comment]
> This is giving following error

You likely just need to kill/restart the ODL process. Once it gets into that error state it needs a restart before it starts working again. High values for NUM_SWITCHES and few CPU cores seem to make it happen more frequently.

> I have reduced NUM_SWITCHES to 6 in wcbench.sh file and no. of cores increased to8 in Vagrant up. Yet I am getting this error.

That should be more than sufficient.

I wasn't able to replicate the failure on my system, for what it's worth.

**Comment by Jaanki** [comment]
Solved...Restarted ODL, reinstalled CBench. No. of switches = 16 and no. of cores = 4 works fine.

**Comment by dfarrell07** [comment]
> Solved...Restarted ODL, reinstalled CBench. No. of switches = 16 and no. of cores = 4 works fine.

Glad it worked out well. :)

I added the restart ODL tip to the relevant error output in a6b871bd02fa8722ce89f7de5ac042a28e401bd5.
