### ISSUE TITLE
Emailed question: ODL with OpenStack - WCBench no result

### ISSUE THREAD

**Issue by dfarrell07** [dfarrell07/wcbench#62]
***Copying an email to this Issues so I can answer it publicly (docs for others, etc).***

I am running ODL Helium pre-built on Ubuntu. Integrated it with OpenStack 3 node architecture. All is working fine. 

I installed WCBench in Ubuntu (made necessary changes in wcbench.sh file). The results are below:

:~/wcbench$ ./wcbench.sh -v -r
Collecting pre-test stats
Running CBench against ODL on 10.107.2.244:6653
cbench: controller benchmarking tool
   running in mode 'latency'
   connecting to controller at 10.107.2.244:6653 
   faking 16 switches offset 1 :: 10 tests each; 10000 ms per test
   with 100000 unique source MACs per switch
   learning destination mac addresses before the test
   starting test with 0 ms delay after features_reply
   ignoring first 1 "warmup" and last 0 "cooldown" loops
   connection delay of 0ms per 1 switch(es)
   debugging info is off
Collecting post-test stats
Collecting time-irrelevant stats
Average responses/second: 0.00

Why is the response zero? results.csv file is generated and attaching the same here.

stats.py results in follwoing error.

:~/wcbench$ ./stats.py -S
Traceback (most recent call last):
  File "./stats.py", line 345, in <module>
    stats_map[stat]()
  File "./stats.py", line 216, in compute_five_load_stats
    self.compute_generic_stats("five_load", self.five_load_col)
  File "./stats.py", line 249, in compute_generic_stats
    generic_stats["min"] = int(numpy.amin(stats_col))
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2209, in amin
    out=out, keepdims=keepdims)
  File "/usr/lib/python2.7/dist-packages/numpy/core/_methods.py", line 21, in _amin
    out=out, keepdims=keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

:~/wcbench$ ./stats.py -G
Traceback (most recent call last):
  File "./stats.py", line 335, in <module>
    graph_map[graph](len(graphs_to_build), graph_num+1)
  File "./stats.py", line 228, in build_five_load_graph
    "Five Minute Load", self.five_load_col)
  File "./stats.py", line 277, in build_generic_graph
    pyplot.plot(self.run_col, data_col, "go")
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 2987, in plot
    ret = ax.plot(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 4137, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 317, in _grab_next_args
    for seg in self._plot_args(remaining, kwargs):
  File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 295, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 237, in _xy_from_xy
    raise ValueError("x and y must have same first dimension")
ValueError: x and y must have same first dimension

Is this because there is not input in the results.csv file? And is the output nill because the controller is busy with OpenStack?

**Comment by dfarrell07** [comment]
> I installed WCBench in Ubuntu (made necessary changes in wcbench.sh file).

It'd be ideal if you'd contribute those back upstream. That's how Open Source projects stay healthy :)

> Is this because there is not input in the results.csv file?

The `stats.py` helper isn't designed to handle `results.csv` that are missing fields, or generally anything other than what's generated by a normal WCBench run. I raised #65 to track this feature request.

> And is the output nill because the controller is busy with OpenStack?

I've seen 0.0 results a number of times, typically it's an ephemeral error that goes away after I restart the ODL process. However, since you've made a bunch of changes to ODL/WCBench to get it running on Ubuntu with OpenStack, I think it's fairly likely that part of that process is the issue. Would really need a **ton** more info. Could try just the Ubuntu changes, get working results merged upstream (we'll verify it works with some rigor at that point), then attempt ODL+OpenStack?

**Comment by Jaanki** [comment]
It'd be ideal if you'd contribute those back upstream. That's how Open Source projects stay healthy :)

Ya sure. Where should I put it?

**Comment by dfarrell07** [comment]
> Am new to github and to contributing to open source projects :)

Ah, well cool, welcome! :)

> Added the repo here Is this correct way or should add it somewhere else?

No, that's not the right way (would be very confusing for users, "which project should I use?", much harder to maintain once they diverge).

As I [describe very briefly in the README](https://github.com/dfarrell07/wcbench#user-content-contributing), you'll want to fork this repo (there's a button on the main page). That'll create a copy you own and can work with. Make committs to your fork to add your changes, then once they are ready submit a pull request (commonly called "PR", there will be a button on your fork's page) to merge your fork and its changes back into the main project. Once you submit it I'll be notified, review it, provide feedback and once it's ready I'll merge your commits into the `master` branch of WCBench.

There's tons of useful documentation about PRs, including:

https://gun.io/blog/how-to-github-fork-branch-and-pull-request/
http://stackoverflow.com/questions/14680711/how-to-do-a-github-pull-request
https://help.github.com/articles/using-pull-requests/

**Comment by dfarrell07** [comment]
Closing this issue, we can handle additional discussion in the PR.
