### ISSUE TITLE
stop ./loop_wcbench.sh

### ISSUE THREAD

**Issue by Jaanki** [dfarrell07/wcbench#63]
I am running ./loop_wcbench.sh -t 2 -r.
How to stop it? Say I want to run wcbench script for 100 times. How do I do this? (Using loop_wcbench ofcourse, but I want the script to stop when run numbers reach 100). I pressed ctrl+c and the process stopped. In the results.csv, there are values for 24 runs. The used ram column varies too. Is there any specific reason for that? Is there any other place where I could ask such general questions?

**Comment by dfarrell07** [comment]
> Say I want to run wcbench script for 100 times. How do I do this?

`loop_wcbench.sh` is a pretty simple helper. It currently isn't designed to loop for N times, but that would be trivial to add. PRs welcome, as always. I raised #64 to track that feature request.

> I pressed ctrl+c and the process stopped. 

That's the expected way.

> In the results.csv, there are values for 24 runs.

This isn't a question, right? This just means you did 24 runs before you killed WCBench.

> The used ram column varies too. Is there any specific reason for that?

The used RAM on systems varies all the time, this is expected. If it *didn't* change, that would be more strange.

> Is there any other place where I could ask such general questions?

Per the [contact section of the README](https://github.com/dfarrell07/wcbench#user-content-contact), the issue tracker (here) is the recommended place. So good job! :+1: :)
