### ISSUE TITLE
Is Cbench topology aware ?

### ISSUE THREAD

**Issue by milangroshev** [dfarrell07/wcbench#69]
I have a question regarding Cbench... as i read in some papers Cbench is a benchmark tool developed to evaluate the performance of OpenFlow controllers. By taking advantage of the Cbench, it is possible to identify performance improvements for OpenFlow controllers based on different environment and system configurations, such as the number of forwarding devices, network topology, overall network workload, type of equipments, forwarding complexity, and overhead of the applications being executed on top of controllers

Is it true that Cbench is topology aware? and how can that be done? 

All i can see Cbench just generates big amount of packet_in messages with different MAC address and do some computations on the packet_out... he is not topology aware and you can not choose the topology... i mean it has two modes latency and throughput... but i can not run it with different typologies  

If somebody has answer to this please write to me :D

**Comment by dfarrell07** [comment]
> Is it true that Cbench is topology aware?

No, it's not.

Per your description, CBench just spams the controller with Openflow packet-in messages from a given number of simulated switches and count flow-mod responses.

You can do stuff with the controller, mininet and CBench (so the controller would have to deal with a topo), but that's not really related to CBench at all.

Hope that helps. :)
