### ISSUE TITLE
Monitor RAM

### ISSUE THREAD

**Issue by stefanoperone** [dfarrell07/wcbench#70]
Hi Daniel,
in wcbench.sh script, we use "free" unix command to check free and used memory on the system running ODL.
In your opinion is possible to change the script to monitor only java process without that we use JConsole for this?

Thanks

**Comment by dfarrell07** [comment]
in wcbench.sh script, we use "free" unix command to check free and used memory on the system running ODL.

True

> In your opinion is possible to change the script to monitor only java process without that we use JConsole for this?

Yeah, should be possible. I actually haven't used JConsole, but as long as it has a CLI that we can install/call/parse-output-of it should be trivial to use it in the same way we use other tools like `free`.

I encourage you to go for it, submit a PR, I'll give feedback and we'll get it merged ASAP. :)

**Comment by dfarrell07** [comment]
@stefanoperone did I answer your question? If so, please close this Issue.

Thanks!

> I encourage you to go for it, submit a PR, I'll give feedback and we'll get it merged ASAP. :)

Also, this. :+1:

**Comment by stefanoperone** [comment]
Perfect ;)
