### ISSUE TITLE
Which VirtualBoxes still supportting the project

### ISSUE THREAD

**Issue by aymeniq** [dfarrell07/wcbench#80]
Hi,
I see that there is no currently live virtualbox supporting Wcbench, there is no longer chef/fedora-20 or boxcutter/fedora22. Is there any luck to install and run the project again?
Thanks

**Comment by dfarrell07** [comment]
This is project is not being maintained, is not recommended. See OpenDaylight's CI for currently used tools, or work in OPNFV for tooling that tests bigger stacks like OpenDaylight+OpenStack.
